[k8s_control_plane]
k8s-control-01 ansible_host=192.168.125.10 ansible_port=22

[k8s_workers]
k8s-worker-01 ansible_host=192.168.125.11 ansible_port=22

[k8s_cluster:children]
k8s_control_plane
k8s_workers

[all:vars]
ansible_user=edoardo
ansible_python_interpreter=/usr/bin/python3
