---
kube_bench_version: "0.15.5"
kube_bench_release_base_url: "https://github.com/aquasecurity/kube-bench/releases/download/v{{ kube_bench_version }}"
kube_bench_arch_map:
  x86_64: amd64
  aarch64: arm64
  arm64: arm64
kube_bench_checksums:
  amd64: 74edba8d7b9eb2f6e7109f50595cfcd5eaf2dd61061629006c17ffa9c5281922
  arm64: 01c97c21278531ee0d02328bc8372d0ae4b0e86ac0100a41be54bf8232df4ff5
kube_bench_arch: "{{ kube_bench_arch_map.get(ansible_facts['architecture'], '') }}"
kube_bench_deb_name: "kube-bench_{{ kube_bench_version }}_linux_{{ kube_bench_arch }}.deb"
kube_bench_deb_path: "/tmp/{{ kube_bench_deb_name }}"
kube_bench_config_path: /etc/kube-bench/cfg/config.yaml

